### ISSUE TITLE
Unrecognizable Error while sending SMS with new Library !

### ISSUE THREAD

**Issue by vinsaTimeparity** [plivo/plivo-dotnet#49]
Hi we are seeing the following error , while sending SMS from ASP.Net MVC using the Plivo 4.0 Package. 

```
 
Unexpected character encountered while parsing value: C. Path '', line 0, position 0.   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Plivo.Client.SystemHttpClient.SendRequest[T](String method, String uri, Dictionary`2 data)
   at Plivo.Client.HttpClient.Update[T](String uri, Dictionary`2 data)
   at Plivo.Resource.Message.MessageInterface.Create(String src, List`1 dst, String text, String type, String url, String method, Nullable`1 log)
```

**This happens while sending extra characters in your Plivo Auth id . While we expect an error , it shuld be Authentication denied , or incorrect Auth id , but the error is a Newtonsoft parsing error.**

.Net Framework: **4.6.2**
Plivo: **4.0.0**
Newtonsoft: **10.0.3**

**Comment by plivo-sdks** [comment]
@vinsaTimeparity Seems like the API is returning an HTML response instead of a JSON response - thus throwing a Newstonsoft parsing error.

A fix will be pushed in one of the upcoming releases.

**Comment by vinsaTimeparity** [comment]
Hi Team,

Can we know when we can expect a resolution for this. As per your timelines you are ending support for older libraries by 30th June 2018 https://www.plivo.com/blog/introducing-plivo-server-side-sdks-v4/ 

When can we expect a resolution to this bug, we have tried the latest 4.1 library and the issue still exists.

**Comment by Gfweis** [comment]
I was told that there would be an update prior to the  end of May... maybe they meant May of 2020.  It can't be that hard to fix :-{

**Comment by nixonsam** [comment]
@vinsaTimeparity This was fixed. Let us know if you are still facing any issues.
